service:
  name: pdf-lambda-puppeteer

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  prune:
    automatic: true
    number: 5

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, 'us-east-1'}
  endpointType: REGIONAL
  stage: ${opt:stage, 'dev'}
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  pdf:
    handler: handler.pdf
    memorySize: 1024 # Setting a higher RAM size to facilitate PDF generation
    timeout: 30
    events:
      - http:
          method: post
          path: /pdf
